spring.application.name=Server
server.error.include-message=always
spring.jpa.hibernate.ddl-auto=validate


server.port=8080
server.address=0.0.0.0

# setup for connecting to local database
spring.datasource.url=jdbc:postgresql://localhost:5432/footballGames
spring.datasource.username=prem_table_user
spring.datasource.password=lafosse
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# spring.datasource.username=postgres